apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muduo-ingress
  namespace: muduo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  ingressClassName: nginx
  rules:
    - host: muduo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: muduo-frontend
                port:
                  number: 80
    - host: api.muduo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: muduo-backend
                port:
                  number: 80
